version: '3'

tasks:
  build:
    cmds:
      - mkdir -p dist
      - go build -o dist/ruf main.go
    desc: 'Builds the application'

  test:
    cmds:
      - go test ./...
    desc: 'Runs all tests'

  validate:
    desc: "Validates the project by building and running tests"
    cmds:
      - task: build
      - task: test